export default () => (
  [{
   user: 'Jose',
   bets:
    [
      ['Russia',3,0,'Saudi Arabia'  ],
      ['Egypt',1,2,'Uruguay'  ],
      ['Russia',0,1,'Egypt'  ],
      ['Uruguay',3,0,'Saudi Arabia'  ],
      ['Uruguay',3,0,'Russia'  ],
      ['Saudi Arabia',1,1,'Egypt'  ],
      ['Portugal',0,1,'Spain'  ],
      ['Morocco',2,2,'Iran'  ],
      ['Portugal',3,0,'Morocco'  ],
      ['Iran',1,2,'Spain'  ],
      ['Iran',1,1,'Portugal'  ],
      ['Spain',1,0,'Morocco'  ],
      ['France',3,0,'Australia'  ],
      ['Peru',1,1,'Denmark'  ],
      ['France',1,1,'Peru'  ],
      ['Denmark',1,2,'Australia'  ],
      ['Denmark',1,2,'France'  ],
      ['Australia',1,1,'Peru'  ],
      ['Argentina',3,0,'Iceland'  ],
      ['Croatia',2,0,'Nigeria'  ],
      ['Argentina',2,2,'Croatia'  ],
      ['Nigeria',1,0,'Iceland'  ],
      ['Nigeria',1,2,'Argentina'  ],
      ['Iceland',1,2,'Croatia'  ],
      ['Brazil',3,1,'Switzerland'  ],
      ['Costa Rica',1,1,'Serbia'  ],
      ['Brazil',1,2,'Costa Rica'  ],
      ['Serbia',1,1,'Switzerland'  ],
      ['Serbia',0,3,'Brazil'  ],
      ['Switzerland',1,1,'Costa Rica'  ],
      ['Germany',2,1,'México'  ],
      ['Sweden',1,2,'South Korea'  ],
      ['Germany',2,0,'Sweden'  ],
      ['South Korea',1,2,'México'  ],
      ['South Korea',1,1,'Germany'  ],
      ['México',0,0,'Sweden'  ],
      ['Belgium',2,0,'Panama'  ],
      ['Tunisia',1,1,'England'  ],
      ['Belgium',2,1,'Tunisia'  ],
      ['England',3,0,'Panama'  ],
      ['England',1,1,'Belgium'  ],
      ['Panama',3,0,'Tunisia'  ],
      ['Poland',3,0,'Senegal'  ],
      ['Colombia',3,0,'Japan'  ],
      ['Poland',1,2,'Colombia'  ],
      ['Japan',0,0,'Senegal'  ],
      ['Japan',2,1,'Poland'  ],
      ['Senegal',0,3,'Colombia'  ]
    ]
  },
  {
    user: 'Luke',
    bets:
    [
    ['Russia',1,1,'Saudi Arabia'  ],
    ['Egypt',1,2,'Uruguay'  ],
    ['Russia',0,2,'Egypt'  ],
    ['Uruguay',3,0,'Saudi Arabia'  ],
    ['Uruguay',3,1,'Russia'  ],
    ['Saudi Arabia',1,2,'Egypt'  ],
    ['Portugal',1,2,'Spain'  ],
    ['Morocco',2,0,'Iran'  ],
    ['Portugal',2,1,'Morocco'  ],
    ['Iran',0,4,'Spain'  ],
    ['Iran',0,2,'Portugal'  ],
    ['Spain',2,1,'Morocco'  ],
    ['France',3,0,'Australia'  ],
    ['Peru',1,0,'Denmark'  ],
    ['France',2,1,'Peru'  ],
    ['Denmark',1,1,'Australia'  ],
    ['Denmark',1,2,'France'  ],
    ['Australia',0,2,'Peru'  ],
    ['Argentina',3,0,'Iceland'  ],
    ['Croatia',2,1,'Nigeria'  ],
    ['Argentina',2,2,'Croatia'  ],
    ['Nigeria',1,0,'Iceland'  ],
    ['Nigeria',1,2,'Argentina'  ],
    ['Iceland',1,2,'Croatia'  ],
    ['Brazil',3,0,'Switzerland'  ],
    ['Costa Rica',0,1,'Serbia'  ],
    ['Brazil',2,0,'Costa Rica'  ],
    ['Serbia',1,0,'Switzerland'  ],
    ['Serbia',1,3,'Brazil'  ],
    ['Switzerland',0,0,'Costa Rica'  ],
    ['Germany',3,1,'México'  ],
    ['Sweden',0,1,'South Korea'  ],
    ['Germany',2,0,'Sweden'  ],
    ['South Korea',1,2,'México'  ],
    ['South Korea',0,2,'Germany'  ],
    ['México',2,1,'Sweden'  ],
    ['Belgium',2,0,'Panama'  ],
    ['Tunisia',0,1,'England'  ],
    ['Belgium',1,0,'Tunisia'  ],
    ['England',3,0,'Panama'  ],
    ['England',2,2,'Belgium'  ],
    ['Panama',0,1,'Tunisia'  ],
    ['Poland',1,1,'Senegal'  ],
    ['Colombia',2,1,'Japan'  ],
    ['Poland',1,2,'Colombia'  ],
    ['Japan',1,2,'Senegal'  ],
    ['Japan',1,1,'Poland'  ],
    ['Senegal',2,2,'Colombia'  ]
    ]
  },
  {
    user: 'Billy',
    bets: [
      ['Russia',1,1,'Saudi Arabia'  ],
      ['Egypt',1,2,'Uruguay'  ],
      ['Russia',0,1,'Egypt'  ],
      ['Uruguay',2,0,'Saudi Arabia'  ],
      ['Uruguay',1,0,'Russia'  ],
      ['Saudi Arabia',1,1,'Egypt'  ],
      ['Portugal',2,1,'Spain'  ],
      ['Morocco',0,0,'Iran'  ],
      ['Portugal',3,1,'Morocco'  ],
      ['Iran',0,2,'Spain'  ],
      ['Iran',0,2,'Portugal'  ],
      ['Spain',2,0,'Morocco'  ],
      ['France',2,0,'Australia'  ],
      ['Peru',0,1,'Denmark'  ],
      ['France',2,1,'Peru'  ],
      ['Denmark',1,1,'Australia'  ],
      ['Denmark',1,2,'France'  ],
      ['Australia',0,1,'Peru'  ],
      ['Argentina',1,0,'Iceland'  ],
      ['Croatia',1,0,'Nigeria'  ],
      ['Argentina',2,1,'Croatia'  ],
      ['Nigeria',1,1,'Iceland'  ],
      ['Nigeria',0,3,'Argentina'  ],
      ['Iceland',1,2,'Croatia'  ],
      ['Brazil',2,0,'Switzerland'  ],
      ['Costa Rica',1,0,'Serbia'  ],
      ['Brazil',2,1,'Costa Rica'  ],
      ['Serbia',1,2,'Switzerland'  ],
      ['Serbia',0,1,'Brazil'  ],
      ['Switzerland',1,1,'Costa Rica'  ],
      ['Germany',2,1,'México'  ],
      ['Sweden',0,1,'South Korea'  ],
      ['Germany',2,0,'Sweden'  ],
      ['South Korea',1,3,'México'  ],
      ['South Korea',1,3,'Germany'  ],
      ['México',1,0,'Sweden'  ],
      ['Belgium',2,0,'Panama'  ],
      ['Tunisia',1,2,'England'  ],
      ['Belgium',1,0,'Tunisia'  ],
      ['England',3,0,'Panama'  ],
      ['England',1,2,'Belgium'  ],
      ['Panama',0,1,'Tunisia'  ],
      ['Poland',0,1,'Senegal'  ],
      ['Colombia',1,0,'Japan'  ],
      ['Poland',1,2,'Colombia'  ],
      ['Japan',0,1,'Senegal'  ],
      ['Japan',1,1,'Poland'  ],
      ['Senegal',1,1,'Colombia'  ]
    ]
  },
  {
    user: 'Adam',
    bets:
    [
      ['Russia',3,1,'Saudi Arabia'  ],
      ['Egypt',1,1,'Uruguay'  ],
      ['Russia',2,1,'Egypt'  ],
      ['Uruguay',3,0,'Saudi Arabia'  ],
      ['Uruguay',2,1,'Russia'  ],
      ['Saudi Arabia',0,2,'Egypt'  ],
      ['Portugal',0,1,'Spain'  ],
      ['Morocco',0,0,'Iran'  ],
      ['Portugal',2,0,'Morocco'  ],
      ['Iran',0,4,'Spain'  ],
      ['Iran',0,3,'Portugal'  ],
      ['Spain',5,0,'Morocco'  ],
      ['France',4,0,'Australia'  ],
      ['Peru',0,1,'Denmark'  ],
      ['France',3,0,'Peru'  ],
      ['Denmark',2,1,'Australia'  ],
      ['Denmark',0,2,'France'  ],
      ['Australia',1,3,'Peru'  ],
      ['Argentina',2,0,'Iceland'  ],
      ['Croatia',2,2,'Nigeria'  ],
      ['Argentina',1,1,'Croatia'  ],
      ['Nigeria',1,1,'Iceland'  ],
      ['Nigeria',0,3,'Argentina'  ],
      ['Iceland',0,2,'Croatia'  ],
      ['Brazil',5,0,'Switzerland'  ],
      ['Costa Rica',3,2,'Serbia'  ],
      ['Brazil',3,0,'Costa Rica'  ],
      ['Serbia',1,1,'Switzerland'  ],
      ['Serbia',0,5,'Brazil'  ],
      ['Switzerland',0,2,'Costa Rica'  ],
      ['Germany',2,0,'México'  ],
      ['Sweden',3,3,'South Korea'  ],
      ['Germany',2,0,'Sweden'  ],
      ['South Korea',0,1,'México'  ],
      ['South Korea',0,4,'Germany'  ],
      ['México',2,2,'Sweden'  ],
      ['Belgium',5,0,'Panama'  ],
      ['Tunisia',1,2,'England'  ],
      ['Belgium',4,0,'Tunisia'  ],
      ['England',3,0,'Panama'  ],
      ['England',2,3,'Belgium'  ],
      ['Panama',0,2,'Tunisia'  ],
      ['Poland',2,2,'Senegal'  ],
      ['Colombia',2,0,'Japan'  ],
      ['Poland',2,1,'Colombia'  ],
      ['Japan',0,3,'Senegal'  ],
      ['Japan',0,2,'Poland'  ],
      ['Senegal',2,3,'Colombia'  ]
    ]
  },
  {
    user: 'Joel',
    bets:
    [
      ['Russia',4,0,'Saudi Arabia'  ],
      ['Egypt',1,2,'Uruguay'  ],
      ['Russia',2,1,'Egypt'  ],
      ['Uruguay',2,1,'Saudi Arabia'  ],
      ['Uruguay',2,2,'Russia'  ],
      ['Saudi Arabia',1,2,'Egypt'  ],
      ['Portugal',2,2,'Spain'  ],
      ['Morocco',1,1,'Iran'  ],
      ['Portugal',3,0,'Morocco'  ],
      ['Iran',0,4,'Spain'  ],
      ['Iran',0,3,'Portugal'  ],
      ['Spain',3,1,'Morocco'  ],
      ['France',4,0,'Australia'  ],
      ['Peru',1,2,'Denmark'  ],
      ['France',3,0,'Peru'  ],
      ['Denmark',2,1,'Australia'  ],
      ['Denmark',1,3,'France'  ],
      ['Australia',0,1,'Peru'  ],
      ['Argentina',3,1,'Iceland'  ],
      ['Croatia',2,2,'Nigeria'  ],
      ['Argentina',3,1,'Croatia'  ],
      ['Nigeria',1,1,'Iceland'  ],
      ['Nigeria',1,3,'Argentina'  ],
      ['Iceland',2,2,'Croatia'  ],
      ['Brazil',4,0,'Switzerland'  ],
      ['Costa Rica',1,2,'Serbia'  ],
      ['Brazil',3,1,'Costa Rica'  ],
      ['Serbia',2,1,'Switzerland'  ],
      ['Serbia',1,3,'Brazil'  ],
      ['Switzerland',1,1,'Costa Rica'  ],
      ['Germany',2,0,'México'  ],
      ['Sweden',1,1,'South Korea'  ],
      ['Germany',2,0,'Sweden'  ],
      ['South Korea',2,1,'México'  ],
      ['South Korea',2,2,'Germany'  ],
      ['México',1,2,'Sweden'  ],
      ['Belgium',3,0,'Panama'  ],
      ['Tunisia',1,2,'England'  ],
      ['Belgium',2,0,'Tunisia'  ],
      ['England',3,1,'Panama'  ],
      ['England',1,1,'Belgium'  ],
      ['Panama',0,1,'Tunisia'  ],
      ['Poland',2,1,'Senegal'  ],
      ['Colombia',2,1,'Japan'  ],
      ['Poland',1,2,'Colombia'  ],
      ['Japan',1,1,'Senegal'  ],
      ['Japan',1,2,'Poland'  ],
      ['Senegal',2,2,'Colombia'  ]
    ]
  },
  {
    user: 'Olu',
    bets:
    [
      ['Russia',2,1,'Saudi Arabia'  ],
      ['Egypt',0,1,'Uruguay'  ],
      ['Russia',1,2,'Egypt'  ],
      ['Uruguay',2,0,'Saudi Arabia'  ],
      ['Uruguay',3,0,'Russia'  ],
      ['Saudi Arabia',0,2,'Egypt'  ],
      ['Portugal',2,0,'Spain'  ],
      ['Morocco',1,1,'Iran'  ],
      ['Portugal',2,1,'Morocco'  ],
      ['Iran',0,4,'Spain'  ],
      ['Iran',0,3,'Portugal'  ],
      ['Spain',2,1,'Morocco'  ],
      ['France',3,0,'Australia'  ],
      ['Peru',1,1,'Denmark'  ],
      ['France',2,0,'Peru'  ],
      ['Denmark',1,1,'Australia'  ],
      ['Denmark',0,3,'France'  ],
      ['Australia',1,1,'Peru'  ],
      ['Argentina',2,0,'Iceland'  ],
      ['Croatia',1,2,'Nigeria'  ],
      ['Argentina',2,1,'Croatia'  ],
      ['Nigeria',0,1,'Iceland'  ],
      ['Nigeria',1,1,'Argentina'  ],
      ['Iceland',0,1,'Croatia'  ],
      ['Brazil',3,0,'Switzerland'  ],
      ['Costa Rica',2,2,'Serbia'  ],
      ['Brazil',2,1,'Costa Rica'  ],
      ['Serbia',1,0,'Switzerland'  ],
      ['Serbia',0,3,'Brazil'  ],
      ['Switzerland',2,2,'Costa Rica'  ],
      ['Germany',3,1,'México'  ],
      ['Sweden',2,2,'South Korea'  ],
      ['Germany',3,0,'Sweden'  ],
      ['South Korea',1,1,'México'  ],
      ['South Korea',0,4,'Germany'  ],
      ['México',2,1,'Sweden'  ],
      ['Belgium',4,0,'Panama'  ],
      ['Tunisia',1,2,'England'  ],
      ['Belgium',3,1,'Tunisia'  ],
      ['England',3,0,'Panama'  ],
      ['England',1,1,'Belgium'  ],
      ['Panama',0,2,'Tunisia'  ],
      ['Poland',1,2,'Senegal'  ],
      ['Colombia',1,1,'Japan'  ],
      ['Poland',1,1,'Colombia'  ],
      ['Japan',2,2,'Senegal'  ],
      ['Japan',2,1,'Poland'  ],
      ['Senegal',1,1,'Colombia'  ]
    ]
  }
]
)
