export default () => (
  [{
   user: 'Jose',
   bets:
    [
      ["Rusia",1,2,"ArabiaSaudi"  ],
      ["Egipto",1,2,"Uruguay"  ],
      ["Rusia",0,1,"Egipto"  ],
      ["Uruguay",3,0,"Arabia Saudí"  ],
      ["Uruguay",3,0,"Rusia"  ],
      ["Arabia Saudí",1,1,"Egipto"  ],
      ["Portugal",0,1,"España"  ],
      ["Marruecos",2,2,"Irán"  ],
      ["Portugal",3,0,"Marruecos"  ],
      ["Irán",1,2,"España"  ],
      ["Irán",1,1,"Portugal"  ],
      ["España",1,0,"Marruecos"  ],
      ["Francia",3,0,"Australia"  ],
      ["Perú",1,1,"Dinamarca"  ],
      ["Francia",1,1,"Perú"  ],
      ["Dinamarca",1,2,"Australia"  ],
      ["Dinamarca",1,2,"Francia"  ],
      ["Australia",1,1,"Perú"  ],
      ["Argentina",3,0,"Islandia"  ],
      ["Croacia",2,0,"Nigeria"  ],
      ["Argentina",2,2,"Croacia"  ],
      ["Nigeria",1,0,"Islandia"  ],
      ["Nigeria",1,2,"Argentina"  ],
      ["Islandia",1,2,"Croacia"  ],
      ["Brasil",3,1,"Suiza"  ],
      ["Costa Rica",1,1,"Serbia"  ],
      ["Brasil",1,2,"Costa Rica"  ],
      ["Serbia",1,1,"Suiza"  ],
      ["Serbia",0,3,"Brasil"  ],
      ["Suiza",1,1,"Costa Rica"  ],
      ["Alemania",2,1,"México"  ],
      ["Suecia",1,2,"Rep. de Corea"  ],
      ["Alemania",2,0,"Suecia"  ],
      ["Rep. de Corea",1,2,"México"  ],
      ["Rep. de Corea",1,1,"Alemania"  ],
      ["México",0,0,"Suecia"  ],
      ["Bélgica",2,0,"Panamá"  ],
      ["Túnez",1,1,"Inglaterra"  ],
      ["Bélgica",2,1,"Túnez"  ],
      ["Inglaterra",3,0,"Panamá"  ],
      ["Inglaterra",1,1,"Bélgica"  ],
      ["Panamá",3,0,"Túnez"  ],
      ["Polonia",3,0,"Senegal"  ],
      ["Colombia",3,0,"Japón"  ],
      ["Polonia",1,2,"Colombia"  ],
      ["Japón",0,0,"Senegal"  ],
      ["Japón",2,1,"Polonia"  ],
      ["Senegal",0,3,"Colombia"  ]
    ]
  },
  {
    user: 'Luke',
    bets:
    [
    ["Rusia",1,1,"ArabiaSaudi"  ],
    ["Egipto",1,2,"Uruguay"  ],
    ["Rusia",0,2,"Egipto"  ],
    ["Uruguay",3,0,"Arabia Saudí"  ],
    ["Uruguay",3,1,"Rusia"  ],
    ["Arabia Saudí",1,2,"Egipto"  ],
    ["Portugal",1,2,"España"  ],
    ["Marruecos",2,0,"Irán"  ],
    ["Portugal",2,1,"Marruecos"  ],
    ["Irán",0,4,"España"  ],
    ["Irán",0,2,"Portugal"  ],
    ["España",2,1,"Marruecos"  ],
    ["Francia",3,0,"Australia"  ],
    ["Perú",1,0,"Dinamarca"  ],
    ["Francia",2,1,"Perú"  ],
    ["Dinamarca",1,1,"Australia"  ],
    ["Dinamarca",1,2,"Francia"  ],
    ["Australia",0,2,"Perú"  ],
    ["Argentina",3,0,"Islandia"  ],
    ["Croacia",2,1,"Nigeria"  ],
    ["Argentina",2,2,"Croacia"  ],
    ["Nigeria",1,0,"Islandia"  ],
    ["Nigeria",1,2,"Argentina"  ],
    ["Islandia",1,2,"Croacia"  ],
    ["Brasil",3,0,"Suiza"  ],
    ["Costa Rica",0,1,"Serbia"  ],
    ["Brasil",2,0,"Costa Rica"  ],
    ["Serbia",1,0,"Suiza"  ],
    ["Serbia",1,3,"Brasil"  ],
    ["Suiza",0,0,"Costa Rica"  ],
    ["Alemania",3,1,"México"  ],
    ["Suecia",0,1,"Rep. de Corea"  ],
    ["Alemania",2,0,"Suecia"  ],
    ["Rep. de Corea",1,2,"México"  ],
    ["Rep. de Corea",0,2,"Alemania"  ],
    ["México",2,1,"Suecia"  ],
    ["Bélgica",2,0,"Panamá"  ],
    ["Túnez",0,1,"Inglaterra"  ],
    ["Bélgica",1,0,"Túnez"  ],
    ["Inglaterra",3,0,"Panamá"  ],
    ["Inglaterra",2,2,"Bélgica"  ],
    ["Panamá",0,1,"Túnez"  ],
    ["Polonia",1,1,"Senegal"  ],
    ["Colombia",2,1,"Japón"  ],
    ["Polonia",1,2,"Colombia"  ],
    ["Japón",1,2,"Senegal"  ],
    ["Japón",1,1,"Polonia"  ],
    ["Senegal",2,2,"Colombia"  ]
    ]
  },
  {
    user: 'Billy',
    bets: [
      ["Rusia",1,1,"ArabiaSaudi"  ],
      ["Egipto",1,2,"Uruguay"  ],
      ["Rusia",0,1,"Egipto"  ],
      ["Uruguay",2,0,"Arabia Saudí"  ],
      ["Uruguay",1,0,"Rusia"  ],
      ["Arabia Saudí",1,1,"Egipto"  ],
      ["Portugal",2,1,"España"  ],
      ["Marruecos",0,0,"Irán"  ],
      ["Portugal",3,1,"Marruecos"  ],
      ["Irán",0,2,"España"  ],
      ["Irán",0,2,"Portugal"  ],
      ["España",2,0,"Marruecos"  ],
      ["Francia",2,0,"Australia"  ],
      ["Perú",0,1,"Dinamarca"  ],
      ["Francia",2,1,"Perú"  ],
      ["Dinamarca",1,1,"Australia"  ],
      ["Dinamarca",1,2,"Francia"  ],
      ["Australia",0,1,"Perú"  ],
      ["Argentina",1,0,"Islandia"  ],
      ["Croacia",1,0,"Nigeria"  ],
      ["Argentina",2,1,"Croacia"  ],
      ["Nigeria",1,1,"Islandia"  ],
      ["Nigeria",0,3,"Argentina"  ],
      ["Islandia",1,2,"Croacia"  ],
      ["Brasil",2,0,"Suiza"  ],
      ["Costa Rica",1,0,"Serbia"  ],
      ["Brasil",2,1,"Costa Rica"  ],
      ["Serbia",1,2,"Suiza"  ],
      ["Serbia",0,1,"Brasil"  ],
      ["Suiza",1,1,"Costa Rica"  ],
      ["Alemania",2,1,"México"  ],
      ["Suecia",0,1,"Rep. de Corea"  ],
      ["Alemania",2,0,"Suecia"  ],
      ["Rep. de Corea",1,3,"México"  ],
      ["Rep. de Corea",1,3,"Alemania"  ],
      ["México",1,0,"Suecia"  ],
      ["Bélgica",2,0,"Panamá"  ],
      ["Túnez",1,2,"Inglaterra"  ],
      ["Bélgica",1,0,"Túnez"  ],
      ["Inglaterra",3,0,"Panamá"  ],
      ["Inglaterra",1,2,"Bélgica"  ],
      ["Panamá",0,1,"Túnez"  ],
      ["Polonia",0,1,"Senegal"  ],
      ["Colombia",1,0,"Japón"  ],
      ["Polonia",1,2,"Colombia"  ],
      ["Japón",0,1,"Senegal"  ],
      ["Japón",1,1,"Polonia"  ],
      ["Senegal",1,1,"Colombia"  ]
    ]
  },
  {
    user: 'Adam',
    bets:
    [
      ["Rusia",3,1,"ArabiaSaudi"  ],
      ["Egipto",1,1,"Uruguay"  ],
      ["Rusia",2,1,"Egipto"  ],
      ["Uruguay",3,0,"Arabia Saudí"  ],
      ["Uruguay",2,1,"Rusia"  ],
      ["Arabia Saudí",0,2,"Egipto"  ],
      ["Portugal",0,1,"España"  ],
      ["Marruecos",0,0,"Irán"  ],
      ["Portugal",2,0,"Marruecos"  ],
      ["Irán",0,4,"España"  ],
      ["Irán",0,3,"Portugal"  ],
      ["España",5,0,"Marruecos"  ],
      ["Francia",4,0,"Australia"  ],
      ["Perú",0,1,"Dinamarca"  ],
      ["Francia",3,0,"Perú"  ],
      ["Dinamarca",2,1,"Australia"  ],
      ["Dinamarca",0,2,"Francia"  ],
      ["Australia",1,3,"Perú"  ],
      ["Argentina",2,0,"Islandia"  ],
      ["Croacia",2,2,"Nigeria"  ],
      ["Argentina",1,1,"Croacia"  ],
      ["Nigeria",1,1,"Islandia"  ],
      ["Nigeria",0,3,"Argentina"  ],
      ["Islandia",0,2,"Croacia"  ],
      ["Brasil",5,0,"Suiza"  ],
      ["Costa Rica",3,2,"Serbia"  ],
      ["Brasil",3,0,"Costa Rica"  ],
      ["Serbia",1,1,"Suiza"  ],
      ["Serbia",0,5,"Brasil"  ],
      ["Suiza",0,2,"Costa Rica"  ],
      ["Alemania",2,0,"México"  ],
      ["Suecia",3,3,"Rep. de Corea"  ],
      ["Alemania",2,0,"Suecia"  ],
      ["Rep. de Corea",0,1,"México"  ],
      ["Rep. de Corea",0,4,"Alemania"  ],
      ["México",2,2,"Suecia"  ],
      ["Bélgica",5,0,"Panamá"  ],
      ["Túnez",1,2,"Inglaterra"  ],
      ["Bélgica",4,0,"Túnez"  ],
      ["Inglaterra",3,0,"Panamá"  ],
      ["Inglaterra",2,3,"Bélgica"  ],
      ["Panamá",0,2,"Túnez"  ],
      ["Polonia",2,2,"Senegal"  ],
      ["Colombia",2,0,"Japón"  ],
      ["Polonia",2,1,"Colombia"  ],
      ["Japón",0,3,"Senegal"  ],
      ["Japón",0,2,"Polonia"  ],
      ["Senegal",2,3,"Colombia"  ]
    ]
  },
  {
    user: 'Joel',
    bets:
    [
      ["Rusia",4,0,"Arabia Saudí"  ],
      ["Egipto",1,2,"Uruguay"  ],
      ["Rusia",2,1,"Egipto"  ],
      ["Uruguay",2,1,"Arabia Saudí"  ],
      ["Uruguay",2,2,"Rusia"  ],
      ["Arabia Saudí",1,2,"Egipto"  ],
      ["Portugal",2,2,"España"  ],
      ["Marruecos",1,1,"Irán"  ],
      ["Portugal",3,0,"Marruecos"  ],
      ["Irán",0,4,"España"  ],
      ["Irán",0,3,"Portugal"  ],
      ["España",3,1,"Marruecos"  ],
      ["Francia",4,0,"Australia"  ],
      ["Perú",1,2,"Dinamarca"  ],
      ["Francia",3,0,"Perú"  ],
      ["Dinamarca",2,1,"Australia"  ],
      ["Dinamarca",1,3,"Francia"  ],
      ["Australia",0,1,"Perú"  ],
      ["Argentina",3,1,"Islandia"  ],
      ["Croacia",2,2,"Nigeria"  ],
      ["Argentina",3,1,"Croacia"  ],
      ["Nigeria",1,1,"Islandia"  ],
      ["Nigeria",1,3,"Argentina"  ],
      ["Islandia",2,2,"Croacia"  ],
      ["Brasil",4,0,"Suiza"  ],
      ["Costa Rica",1,2,"Serbia"  ],
      ["Brasil",3,1,"Costa Rica"  ],
      ["Serbia",2,1,"Suiza"  ],
      ["Serbia",1,3,"Brasil"  ],
      ["Suiza",1,1,"Costa Rica"  ],
      ["Alemania",2,0,"México"  ],
      ["Suecia",1,1,"Rep. de Corea"  ],
      ["Alemania",2,0,"Suecia"  ],
      ["Rep. de Corea",2,1,"México"  ],
      ["Rep. de Corea",2,2,"Alemania"  ],
      ["México",1,2,"Suecia"  ],
      ["Bélgica",3,0,"Panamá"  ],
      ["Túnez",1,2,"Inglaterra"  ],
      ["Bélgica",2,0,"Túnez"  ],
      ["Inglaterra",3,1,"Panamá"  ],
      ["Inglaterra",1,1,"Bélgica"  ],
      ["Panamá",0,1,"Túnez"  ],
      ["Polonia",2,1,"Senegal"  ],
      ["Colombia",2,1,"Japón"  ],
      ["Polonia",1,2,"Colombia"  ],
      ["Japón",1,1,"Senegal"  ],
      ["Japón",1,2,"Polonia"  ],
      ["Senegal",2,2,"Colombia"  ]
    ]
  },
  {
    user: 'Olu',
    bets:
    [
      ["Rusia",2,1,"Arabia Saudí"  ],
      ["Egipto",0,1,"Uruguay"  ],
      ["Rusia",1,2,"Egipto"  ],
      ["Uruguay",2,0,"Arabia Saudí"  ],
      ["Uruguay",3,0,"Rusia"  ],
      ["Arabia Saudí",0,2,"Egipto"  ],
      ["Portugal",2,0,"España"  ],
      ["Marruecos",1,1,"Irán"  ],
      ["Portugal",2,1,"Marruecos"  ],
      ["Irán",0,4,"España"  ],
      ["Irán",0,3,"Portugal"  ],
      ["España",2,1,"Marruecos"  ],
      ["Francia",3,0,"Australia"  ],
      ["Perú",1,1,"Dinamarca"  ],
      ["Francia",2,0,"Perú"  ],
      ["Dinamarca",1,1,"Australia"  ],
      ["Dinamarca",0,3,"Francia"  ],
      ["Australia",1,1,"Perú"  ],
      ["Argentina",2,0,"Islandia"  ],
      ["Croacia",1,2,"Nigeria"  ],
      ["Argentina",2,1,"Croacia"  ],
      ["Nigeria",0,1,"Islandia"  ],
      ["Nigeria",1,1,"Argentina"  ],
      ["Islandia",0,1,"Croacia"  ],
      ["Brasil",3,0,"Suiza"  ],
      ["Costa Rica",2,2,"Serbia"  ],
      ["Brasil",2,1,"Costa Rica"  ],
      ["Serbia",1,0,"Suiza"  ],
      ["Serbia",0,3,"Brasil"  ],
      ["Suiza",2,2,"Costa Rica"  ],
      ["Alemania",3,1,"México"  ],
      ["Suecia",2,2,"Rep. de Corea"  ],
      ["Alemania",3,0,"Suecia"  ],
      ["Rep. de Corea",1,1,"México"  ],
      ["Rep. de Corea",0,4,"Alemania"  ],
      ["México",2,1,"Suecia"  ],
      ["Bélgica",4,0,"Panamá"  ],
      ["Túnez",1,2,"Inglaterra"  ],
      ["Bélgica",3,1,"Túnez"  ],
      ["Inglaterra",3,0,"Panamá"  ],
      ["Inglaterra",1,1,"Bélgica"  ],
      ["Panamá",0,2,"Túnez"  ],
      ["Polonia",1,2,"Senegal"  ],
      ["Colombia",1,1,"Japón"  ],
      ["Polonia",1,1,"Colombia"  ],
      ["Japón",2,2,"Senegal"  ],
      ["Japón",2,1,"Polonia"  ],
      ["Senegal",1,1,"Colombia"  ]
    ]
  }
]
)
